version: '3.8'

services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe
    environment:
      - ORACLE_PWD=oracle
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus system/oracle@localhost:1521/XEPDB1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      # Optional: Mount your SQL script into the container so you can run it if needed
      - ./src/main/resources/db/script.sql:/app/script.sql

  techdesk-backend:
    build: .
    container_name: techdesk-backend
    ports:
      - "8080:8080"
    depends_on:
      oracle-xe:
        condition: service_healthy
    environment:
      # Override Spring Boot properties to point to the Oracle container
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-xe:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=techdesk
      - SPRING_DATASOURCE_PASSWORD=techdesk_password
