-- Create APP_USERS table
CREATE TABLE APP_USERS (
    ID       RAW(16)            NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR2(255 CHAR)   NOT NULL,
    ROLE     VARCHAR2(255 CHAR)   NOT NULL
        CHECK (ROLE IN ('ADMIN', 'EMPLOYEE', 'IT_SUPPORT')),
    USERNAME VARCHAR2(50 CHAR)    NOT NULL
        CONSTRAINT UKSPSNWR241E9K9C8P5XL4K45IH UNIQUE
);
/

-- Create TICKETS table
CREATE TABLE TICKETS (
    ID          RAW(16)             NOT NULL PRIMARY KEY,
    CATEGORY    VARCHAR2(255 CHAR)  NOT NULL CHECK (CATEGORY IN ('NETWORK', 'HARDWARE', 'SOFTWARE', 'OTHER')),
    CREATED_AT  TIMESTAMP(6)        NOT NULL,
    DESCRIPTION VARCHAR2(2000 CHAR) NOT NULL,
    PRIORITY    VARCHAR2(255 CHAR)  NOT NULL CHECK (PRIORITY IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    STATUS      VARCHAR2(255 CHAR)  NOT NULL CHECK (STATUS IN ('NEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
    TITLE       VARCHAR2(100 CHAR)  NOT NULL,
    UPDATED_AT  TIMESTAMP(6),
    ASSIGNED_TO RAW(16) CONSTRAINT FK8QDL5563I4OEDORMQA9IBOQXM REFERENCES APP_USERS,
    CREATED_BY  RAW(16) NOT NULL CONSTRAINT FKJM2E5HMCL3L28M1K9BVQR529J REFERENCES APP_USERS
);
/

-- Create COMMENTS table
CREATE TABLE COMMENTS (
    ID         RAW(16)             NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP(6)        NOT NULL,
    TEXT       VARCHAR2(1000 CHAR) NOT NULL,
    TICKET_ID  RAW(16)             NOT NULL
        CONSTRAINT FKJ7VC0AIGR2M5MEW52V7DDT4FO REFERENCES TICKETS,
    USER_ID    RAW(16)             NOT NULL
        CONSTRAINT FK8WYOM37KC61AD0JBHA24MIOO8 REFERENCES APP_USERS
);
/

-- Create TICKET_AUDIT_LOGS table
CREATE TABLE TICKET_AUDIT_LOGS (
    ID          RAW(16)             NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR2(2000 CHAR) NOT NULL,
    LOG_TYPE    VARCHAR2(255 CHAR)  NOT NULL CHECK (LOG_TYPE IN ('STATUS_CHANGE', 'COMMENT_ADDED')),
    TIMESTAMP   TIMESTAMP(6)        NOT NULL,
    CHANGED_BY  RAW(16)             NOT NULL
        CONSTRAINT FKS7AY8X6CD1WOQE6IY8PTKW255 REFERENCES APP_USERS,
    TICKET_ID   RAW(16)             NOT NULL
        CONSTRAINT FKBMO6OBTLQCHTCFB31157KJDE REFERENCES TICKETS
);
/

