spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: techdesk
    password: techdesk_password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true

server:
  port: 8080
